version: '3.8'

services:
  whoami:
    image: containous/whoami
    restart: unless-stopped
    ports:
      - "8082:80"
    labels:
      - "dockge.description=A simple whoami service that displays container information"
      - "dockge.icon=server"