version: '3.8'

services:
  whoami:
    image: containous/whoami
    restart: unless-stopped
    ports:
      - "8082:80"
    networks:
      - monitoring
    labels:
      - "dockge.description=Simple test service that displays container information"
      - "dockge.icon=help-circle"
      - "dockge.note=Used for testing Uptime-Kuma monitoring"
      - "uptime-kuma.monitor=true"
      - "uptime-kuma.monitor.name=Whoami Test Service"
      - "uptime-kuma.monitor.type=http"
      - "uptime-kuma.monitor.url=http://whoami:80"
      - "uptime-kuma.monitor.interval=30"
      - "uptime-kuma.monitor.retryInterval=10"
