version: '3.8'

services:
  ollama:
    image: ollama/ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    labels:
      - "dockge.description=Ollama - Run AI models locally"
      - "dockge.icon=cpu"

volumes:
  ollama_data:
    name: ollama