services:
  tts-api:
    image: ghcr.io/bmv234/tts-v2-api-server:latest
    restart: unless-stopped
    ports:
      - "8055:8000"  # External port 8050 mapped to internal port 8000
    volumes:
      - tts_models:/app/models  # Persist downloaded models
      - tts_cache:/app/cache    # Cache directory for generated audio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    labels:
      - "dockge.description=Text-to-Speech V2 API Server"
      - "dockge.icon=mic"
      - "dockge.note=GPU-accelerated TTS service"

volumes:
  tts_models:
    name: tts-models
  tts_cache:
    name: tts-cache