services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Point to parent directory's stacks folder
      - ${PWD}/../stacks:/opt/stacks
      - ${PWD}/../data:/app/data
    environment:
      # Point Dockge to the absolute path inside container
      - DOCKGE_STACKS_DIR=/opt/stacks
      - TZ=UTC
